import NextAuth, { type NextAuthConfig } from "next-auth"
import GitHub from "next-auth/providers/github"
import Google from "next-auth/providers/google"
import { KyselyAdapter } from "@auth/kysely-adapter"

// Lib
import { db } from "@lib/database.lib"

const config: NextAuthConfig = {
  /**
   * Ignore issues as DB types generated by kysely-codegen are wrong.
   *
   * There are many threads already open on various issues (mismatched data types,
   * interfaces instead of types, etc.) that it's hard to pin-point a specific resolution.
   *
   * For now, the fix is a combination of manual typing and type-casting.
   *
   * @see https://github.com/nextauthjs/next-auth/issues/10441#issuecomment-2215188319
   */

  // @ts-expect-error See above
  adapter: KyselyAdapter(db),
  providers: [GitHub, Google],
  pages: {
    signIn: "/sign-in",
  },
}

export const { handlers, signIn, signOut, auth } = NextAuth(config)
